#!/usr/bin/env bash
source $(dirname $0)/../lib/functions.inc

BROWSER="my_browser"

function oneTimeSetUp() {
  MAILCAP_FILE=$(dirname $0)/testfiles/mailcap
  TXTSYMLINK=$(dirname $0)/testfiles/symlink.txt
  TXTFILE=$(dirname $0)/testfiles/test.txt
  MDFILE=$(dirname $0)/testfiles/test.md
  MKDFILE=$(dirname $0)/testfiles/test.mkd
  MARKDOWNFILE=$(dirname $0)/testfiles/test.markdown
}

function testInputType() {
  assertEquals "existent file"      "file"              "$(input_type ${TXTFILE})"
  assertEquals "nonexistent file"   ""                  "$(input_type xxx)"
  assertEquals "http://"            "http"              "$(input_type "http://www.google.com")"
  assertEquals "ftp://"             "ftp"               "$(input_type "ftp://www.google.com")"
  assertEquals "https://"           "https"             "$(input_type "https://www.google.com")"
  assertEquals "blah:// stderr"     "unknown protocol"  "$(input_type "blah://www.google.com" 2>&1)"
  assertEquals "blah:// stdout"     ""                  "$(input_type "blah://www.google.com" 2>/dev/null)"

  assertTrue   "existent file returns true"             "input_type ${TXTFILE}"
  assertFalse  "nonexistent file returns false"         "input_type xxx"
  assertTrue   "https:// status"                        "input_type 'https://www.google.com'"
  assertTrue   "http:// status"                         "input_type 'http://www.google.com'"
  assertTrue   "ftp:// status"                          "input_type 'ftp://www.google.com'"
  assertFalse  "blah:// status"                         "input_type 'blah://www.google.com' >&/dev/null"
}

function testMimetype() {
  assertEquals "$(basename ${TXTFILE})"       "text/plain"    "$(mimetype "${TXTFILE}")"
  assertEquals "$(basename ${MDFILE})"        "text/markdown" "$(mimetype "${MDFILE}")"
  assertEquals "$(basename ${MKDFILE})"       "text/markdown" "$(mimetype "${MKDFILE}")"
  assertEquals "$(basename ${MARKDOWNFILE})"  "text/markdown" "$(mimetype "${MARKDOWNFILE}")"
  assertEquals "$(basename ${TXTSYMLINK})"    "text/plain"    "$(mimetype "${TXTSYMLINK}")"
}

testMailcapCmd() {
  assertEquals "text/markdown"  "markdown_cmd %s"   "$(mailcap_cmd 'text/markdown')"
  assertEquals "text/plain"     "plaintext_cmd %s"  "$(mailcap_cmd 'text/plain')"
}

testCmd() {
  assertEquals "${MDFILE}"              "markdown_cmd ${MDFILE}"            "$(cmd ${MDFILE})"
  assertEquals "${TXTFILE}"             "plaintext_cmd ${TXTFILE}"          "$(cmd ${TXTFILE})"
  assertEquals "http://www.google.com"  "${BROWSER} http://www.google.com"  "$(cmd "http://www.google.com")"
  assertEquals "blah://nothing"         ""                                  "$(cmd "blah://nothing")"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
