#!/usr/bin/env bash
source $(dirname $0)/../lib/mailcap.inc

function oneTimeSetUp() {
  LOPEN_MAILCAP_FILE=$(dirname $0)/testfiles/mailcap
}

testMailcapCmd() {
  c="mailcap_cmd"
  assertEquals "text/markdown"  "markdown_cmd %s"   "$($c 'text/markdown')"
  assertEquals "text/plain"     "plaintext_cmd %s"  "$($c 'text/plain')"
  assertEquals "image/jpeg"     "jpeg_viewer %s"    "$($c 'image/jpeg')"
  assertEquals "image/png"      "image_viewer %s"   "$($c 'image/png')"
}

testMailcapFlags() {
  c="mailcap_flags"
  assertEquals "text/markdown"  "copiousoutput"     "$($c 'text/markdown')"
  assertEquals "text/plain"     ""                  "$($c 'text/plain')"
}

source $(dirname $0)/../vendor/shunit.inc
